### ISSUE TITLE
请问项目如何运行，可否提供一下运行步骤

### ISSUE THREAD

**Issue by zwkkk** [DrssXpro/virtualwaterfall-demo#1]
您好 我是前端初学者，想请问项目如何运行，可否提供一下运行步骤，十分感谢！

**Comment by DrssXpro** [comment]
需要先去安装 Node 环境，Node 自带 npm，通过 npm 全局安装 pnpm，之后将项目代码拉下来在根目录下执行 pnpm install 安装项目依赖，最后 pnpm run dev 项目就跑起来了，这些关键词直接网上搜跟着官方文档安装就有
